# File paths
data:
  cleaned: data/processed/cleaned.pkl
  features: data/processed/features.pkl
  targets: data/processed/targets.pkl

reference:
  features_map: data/reference/features_map.pkl
  targets_map: data/reference/targets_map.pkl

perseus:
  raw_dir: data/raw/treebank_data-master/v1.6/greek/data
  tagset: data/raw/treebank_data-master/v2.0/Greek/TAGSETS.xml
  raw: data/interim/perseus_raw.pkl
  normalized: data/interim/perseus_normalized.pkl

# Training configs
runs:
  runs_dir: data/runs
  run:

train:
  clf_module: cgpos.model.multinomial_naive_bayes
  clfs: [MultinomialNaiveBayes, StupidBayes]
  test_split:
    n_splits: 1
    train_size: 0.9
    random_state: 30
  tune_split:
    n_splits: 5
    train_size: 0.8888
    random_state: 20
  f1_average: "macro"
  export_pred: False

eval:
  models_dir: models

param_grid:
  MultinomialNaiveBayes:
    alpha:
      start: 0.1
      stop: 1
      step: 0.1
    ngram_range:
      depth: 6
  StupidBayes:
    ngram_depth:
      start: 4
      stop: 9
